import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, signInWithRedirect, getRedirectResult, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, collection, getDocs, updateDoc, serverTimestamp, orderBy, query } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';
const config=window.TAXI_PAY_FIREBASE_CONFIG||{};
const gate=document.getElementById('adminAuthGate'), msg=document.getElementById('adminMessage'), usersBody=document.getElementById('usersBody'), allowBody=document.getElementById('allowlistBody');
function fmt(t){try{return t?.toDate().toLocaleString('ja-JP')||'—'}catch{return'—'}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showGate(text){document.body.classList.add('auth-pending');gate.hidden=false;if(text)msg.textContent=text}
function showPage(){document.body.classList.remove('auth-pending');gate.hidden=true}
async function sha256(text){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text.trim()));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function positiveInteger(v,label){const n=Number(v);if(!Number.isInteger(n)||n<1)throw new Error(`${label}は1人以上の整数で入力してください。`);return n}
if(!config.enabled||config.apiKey==='REPLACE_ME'){showGate('Firebaseの初期設定が未完了です。')}else{
 const app=initializeApp(config), auth=getAuth(app), db=getFirestore(app), provider=new GoogleAuthProvider(); provider.setCustomParameters({prompt:'select_account'});
 document.getElementById('adminGoogleLogin').onclick=async()=>{try{await signInWithPopup(auth,provider)}catch(e){if(e?.code==='auth/popup-blocked')await signInWithRedirect(auth,provider);else msg.textContent='Googleログインできませんでした。'}};
 document.getElementById('adminLogout').onclick=()=>signOut(auth);
 document.getElementById('allowlistForm').onsubmit=async e=>{e.preventDefault();const status=document.getElementById('allowlistStatus');try{const email=document.getElementById('allowEmail').value.trim().toLowerCase();const displayName=document.getElementById('allowDisplayName').value.trim();if(!email)throw new Error('メールアドレスを入力してください。');const ref=doc(db,'betaAllowlist',email);const snap=await getDoc(ref);if(snap.exists())throw new Error('このメールアドレスは既に許可リストへ登録されています。');await setDoc(ref,{email,displayName,enabled:true,invitationUsed:false,registeredUid:null,createdAt:serverTimestamp()});status.textContent='許可リストへ追加しました。';e.currentTarget.reset();await loadAllowlist()}catch(err){status.textContent=err?.message||'追加できませんでした。'}};
 document.getElementById('codeForm').onsubmit=async e=>{e.preventDefault();const status=document.getElementById('codeStatus');try{const code=document.getElementById('newAccessCode').value.trim(),maxUses=positiveInteger(document.getElementById('newAccessMaxUses').value,'利用上限');if(!code)throw new Error('招待コードを入力してください。');const ref=doc(db,'accessCodes',await sha256(code));if((await getDoc(ref)).exists())throw new Error('このコードは既に登録されています。');await setDoc(ref,{active:true,version:'v1.2-beta',maxUses,usageCount:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});status.textContent=`新しい招待コードを発行しました。利用上限は${maxUses}人です。`;e.currentTarget.reset();document.getElementById('newAccessMaxUses').value='10'}catch(err){status.textContent=err?.message||'発行できませんでした。'}};
 document.getElementById('limitForm').onsubmit=async e=>{e.preventDefault();const status=document.getElementById('limitStatus');try{const code=document.getElementById('limitAccessCode').value.trim(),maxUses=positiveInteger(document.getElementById('limitMaxUses').value,'新しい利用上限');const ref=doc(db,'accessCodes',await sha256(code)),snap=await getDoc(ref);if(!snap.exists())throw new Error('入力された招待コードは登録されていません。');const data=snap.data(),uses=Number(data.usageCount||0);if(maxUses<uses)throw new Error(`現在${uses}人が登録済みです。`);await updateDoc(ref,{maxUses,active:true,version:'v1.2-beta',updatedAt:serverTimestamp()});status.textContent=`利用上限を${maxUses}人へ変更しました。`}catch(err){status.textContent=err?.message||'変更できませんでした。'}};
 async function loadAllowlist(){const snap=await getDocs(collection(db,'betaAllowlist'));allowBody.innerHTML='';const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>a.id.localeCompare(b.id));for(const a of rows){const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(a.displayName||'—')}</td><td>${esc(a.id)}</td><td>${a.enabled===true?'許可':'停止'}</td><td>${a.invitationUsed===true?'登録済み':'未登録'}</td><td><button type="button" data-allow-email="${esc(a.id)}" data-enabled="${a.enabled===true}">${a.enabled===true?'利用停止':'利用再開'}</button></td>`;allowBody.appendChild(tr)}}
 allowBody.onclick=async e=>{const b=e.target.closest('button[data-allow-email]');if(!b)return;const next=b.dataset.enabled!=='true';await updateDoc(doc(db,'betaAllowlist',b.dataset.allowEmail),{enabled:next,updatedAt:serverTimestamp()});await loadAllowlist()};
 async function loadUsers(){document.getElementById('adminStatus').textContent='読み込み中…';const snap=await getDocs(query(collection(db,'users'),orderBy('createdAt','desc')));const users=snap.docs.map(d=>({id:d.id,...d.data()}));usersBody.innerHTML='';let active=0,locked=0;for(const u of users){u.status==='active'?active++:locked++;const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(u.name||'—')}</td><td>${esc(u.email||'—')}</td><td>${esc(u.plan||'—')}</td><td>${u.status==='active'?'利用中':'利用停止'}</td><td>${fmt(u.createdAt)}</td><td>${fmt(u.lastLoginAt)}</td><td><button type="button" data-user-id="${esc(u.id)}" data-status="${esc(u.status)}">${u.status==='active'?'利用停止':'利用再開'}</button></td>`;usersBody.appendChild(tr)}document.getElementById('userCount').textContent=`${users.length}人`;document.getElementById('activeCount').textContent=`${active}人`;document.getElementById('lockedCount').textContent=`${locked}人`;document.getElementById('adminStatus').textContent=''}
 usersBody.onclick=async e=>{const b=e.target.closest('button[data-user-id]');if(!b)return;const next=b.dataset.status==='active'?'locked':'active';await updateDoc(doc(db,'users',b.dataset.userId),{status:next,statusUpdatedAt:serverTimestamp()});await loadUsers()};
 getRedirectResult(auth).catch(()=>{});
 onAuthStateChanged(auth,async user=>{if(!user)return showGate();const admin=await getDoc(doc(db,'admins',user.uid));if(!admin.exists()){await signOut(auth);return showGate('このGoogleアカウントには管理者権限がありません。')}showPage();await Promise.all([loadAllowlist(),loadUsers()])});
}
